# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - python=3.11.4
 - pangeo-notebook==2023.05.15 
 - jupyterlab-nvdashboard
 - pytorch==2.1.0=*cuda112*
 - torchvision>=0.15.1=*cuda112*
 - torchgeo
 - onnxruntime==1.16.3
 - onnx==1.15.0
 - planetary-computer==1.0.0
 # Specific for distribute client / server compat
 - tornado==6.3.2
 - cloudpickle==2.2.1
#- msgpack==1.0.5
