# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - python==3.11.7
 - pangeo-notebook==2023.12.17
 - jupyterlab-nvdashboard
 - gpytorch
 - pytorch==2.1.0=*cuda118*
 - torchvision>=0.15.1=*cuda118*
 - torchgeo
 # Inference deps
 - onnxruntime #==1.16.3
 - onnx #==1.15.0
 - planetary-computer
 # Specific for distribute client / server compat
 - tornado #==6.3.2
 - cloudpickle #==2.2.1
 - cryptography>=41.0.6 # get quay to stop complaining
#- msgpack==1.0.5
 - gdown
 # Training deps
 - mmcv
 - cupy
 - mmdet
 - pip:
   - onnxruntime-gpu
   - yolox_backbone
   - cucim
